
import scripts.staging.stages;
import crafttweaker.liquid.ILiquidStack;

print("~~~ Begin Liquid Staging ~~~");

function StageFlorb(liquidString as string, stageToSetTo as mods.zenstages.Stage)
{
	var FlorbData as crafttweaker.data.IData = {Fluid: liquidString};
	mods.ItemStages.addItemStage(stageToSetTo.stage, <thermalexpansion:florb>.withTag(FlorbData));
}

function StageFluidPattern(liquidString as string, stageToSetTo as mods.zenstages.Stage)
{
	var FluidPatternData as crafttweaker.data.IData = {Fluid: {FluidName: liquidString, Amount: 1000}};
	mods.ItemStages.addItemStage(stageToSetTo.stage, <extracells:pattern.fluid>.withTag(FluidPatternData));
}

function StageForestryCapsule(liquidObject as ILiquidStack, stageToSetTo as mods.zenstages.Stage)
{
	var liquidString as string = scripts.helpers.getLiquidStringFromObject(liquidObject);

	//If the liquid can be held in a Wax Capsule, stage that too.
	if (liquidObject.definition.temperature <= 300)
	{
		var WaxCapsuleData as crafttweaker.data.IData = {Fluid: {FluidName: liquidString, Amount: 1000}};
		mods.ItemStages.addItemStage(stageToSetTo.stage, <forestry:capsule:1>.withTag(WaxCapsuleData));
	}

	var TinCanData as crafttweaker.data.IData = {Fluid: {FluidName: liquidString, Amount: 1000}};
	mods.ItemStages.addItemStage(stageToSetTo.stage, <forestry:can:1>.withTag(TinCanData));

	var FrefractoryCapsuleData as crafttweaker.data.IData = {Fluid: {FluidName: liquidString, Amount: 1000}};
	mods.ItemStages.addItemStage(stageToSetTo.stage, <forestry:refractory:1>.withTag(FrefractoryCapsuleData));
}

var liquidStages as mods.zenstages.Stage[crafttweaker.liquid.ILiquidStack] =
{
	<liquid:aerotheum> : stages.progression2,
	<liquid:alchemical_redstone> : stages.Embers3,
	<liquid:alubrass> : stages.progression2,
	<liquid:alugentum> : stages.progression3,
	<liquid:alumina> : stages.progression3,
	<liquid:aluminum> : stages.progression2,
	<liquid:americium_241> : stages.progression3,
	<liquid:americium_241_fluoride> : stages.progression3,
	<liquid:americium_241_fluoride_flibe> : stages.progression3,
	<liquid:americium_242> : stages.progression3,
	<liquid:americium_242_fluoride> : stages.progression3,
	<liquid:americium_242_fluoride_flibe> : stages.progression3,
	<liquid:americium_243> : stages.progression3,
	<liquid:americium_243_fluoride> : stages.progression3,
	<liquid:americium_243_fluoride_flibe> : stages.progression3,
	<liquid:ammonia> : stages.progression2,
	<liquid:ancient_debris> : stages.progression1,
	<liquid:ardite> : stages.progression2,
	<liquid:arsenic> : stages.progression3,
	<liquid:astral_starmetal> : stages.AstralSorcery1,
	<liquid:awakened_draconium> : stages.progression3,
	<liquid:bas> : stages.progression2,
	<liquid:beetroot_soup> : stages.progression1,
	<liquid:bef2> : stages.progression3,
	<liquid:berkelium_247> : stages.progression3,
	<liquid:berkelium_247_fluoride> : stages.progression3,
	<liquid:berkelium_247_fluoride_flibe> : stages.progression3,
	<liquid:berkelium_248> : stages.progression3,
	<liquid:berkelium_248_fluoride> : stages.progression3,
	<liquid:berkelium_248_fluoride_flibe> : stages.progression3,
	<liquid:beryllium> : stages.progression2,
	<liquid:biocrude> : stages.progression2,
	<liquid:biofuel> : stages.progression2,
	<liquid:biomass> : stages.progression2,
	<liquid:black_iron> : stages.progression1,
	<liquid:blockfluidantimatter> : stages.BloodMagic3,
	<liquid:blockfluiddirt> : stages.BloodMagic3,
	<liquid:blood> : stages.progression1,
	<liquid:blueslime> : stages.progression1,
	<liquid:borax_solution> : stages.progression3,
	<liquid:boric_acid> : stages.progression2,
	<liquid:boron> : stages.progression2,
	<liquid:boron10> : stages.progression2,
	<liquid:boron11> : stages.progression2,
	<liquid:boron_nitride_solution> : stages.progression2,
	<liquid:brass> : stages.progression2,
	<liquid:brine> : stages.progression2,
	<liquid:bronze> : stages.progression2,
	<liquid:calcium_sulfate_solution> : stages.progression3,
	<liquid:californium_249> : stages.progression3,
	<liquid:californium_249_fluoride> : stages.progression3,
	<liquid:californium_249_fluoride_flibe> : stages.progression3,
	<liquid:californium_250> : stages.progression3,
	<liquid:californium_250_fluoride> : stages.progression3,
	<liquid:californium_250_fluoride_flibe> : stages.progression3,
	<liquid:californium_251> : stages.progression3,
	<liquid:californium_251_fluoride> : stages.progression3,
	<liquid:californium_251_fluoride_flibe> : stages.progression3,
	<liquid:californium_252> : stages.progression3,
	<liquid:californium_252_fluoride> : stages.progression3,
	<liquid:californium_252_fluoride_flibe> : stages.progression3,
	<liquid:carbon_dioxide> : stages.progression3,
	<liquid:carbon_monoxide> : stages.progression3,
	<liquid:chocolate_liquor> : stages.progression1,
	<liquid:chromium> : stages.progression3,
	<liquid:clay> : stages.progression1,
	<liquid:cloud_seed> : stages.progression2,
	<liquid:cloud_seed_concentrated> : stages.progression2,
	<liquid:coal> : stages.progression1,
	<liquid:cobalt> : stages.progression2,
	<liquid:cocoa_butter> : stages.progression1,
	<liquid:condensate_water> : stages.progression3,
	<liquid:conductive_iron> : stages.progression1,
	<liquid:constantan> : stages.progression2,
	<liquid:construction_alloy> : stages.progression2,
	<liquid:copper> : stages.progression2,
	<liquid:copper_nak> : stages.progression3,
	<liquid:copper_nak_hot> : stages.progression3,
	<liquid:corium> : stages.progression3,
	<liquid:creosote> : stages.progression1,
	<liquid:crude_oil> : stages.progression3,
	<liquid:crude_steel> : stages.progression1,
	<liquid:cryotheum> : stages.progression2,
	<liquid:cryotheum_nak> : stages.progression3,
	<liquid:cryotheum_nak_hot> : stages.progression3,
	<liquid:crystalline_alloy> : stages.progression3,
	<liquid:crystalline_pink_slime> : stages.progression3,
	<liquid:curium_243> : stages.progression3,
	<liquid:curium_243_fluoride> : stages.progression3,
	<liquid:curium_243_fluoride_flibe> : stages.progression3,
	<liquid:curium_245> : stages.progression3,
	<liquid:curium_245_fluoride> : stages.progression3,
	<liquid:curium_245_fluoride_flibe> : stages.progression3,
	<liquid:curium_246> : stages.progression3,
	<liquid:curium_246_fluoride> : stages.progression3,
	<liquid:curium_246_fluoride_flibe> : stages.progression3,
	<liquid:curium_247> : stages.progression3,
	<liquid:curium_247_fluoride> : stages.progression3,
	<liquid:curium_247_fluoride_flibe> : stages.progression3,
	<liquid:dark_chocolate> : stages.progression1,
	<liquid:dark_steel> : stages.progression2,
	<liquid:dawnstone> : stages.Embers2,
	<liquid:depleted_fuel_hea_242> : stages.progression3,
	<liquid:depleted_fuel_hea_242_fluoride> : stages.progression3,
	<liquid:depleted_fuel_hea_242_fluoride_flibe> : stages.progression3,
	<liquid:depleted_fuel_heb_248> : stages.progression3,
	<liquid:depleted_fuel_heb_248_fluoride> : stages.progression3,
	<liquid:depleted_fuel_heb_248_fluoride_flibe> : stages.progression3,
	<liquid:depleted_fuel_hecf_249> : stages.progression3,
	<liquid:depleted_fuel_hecf_249_fluoride> : stages.progression3,
	<liquid:depleted_fuel_hecf_249_fluoride_flibe> : stages.progression3,
	<liquid:depleted_fuel_hecf_251> : stages.progression3,
	<liquid:depleted_fuel_hecf_251_fluoride> : stages.progression3,
	<liquid:depleted_fuel_hecf_251_fluoride_flibe> : stages.progression3,
	<liquid:depleted_fuel_hecm_243> : stages.progression3,
	<liquid:depleted_fuel_hecm_243_fluoride> : stages.progression3,
	<liquid:depleted_fuel_hecm_243_fluoride_flibe> : stages.progression3,
	<liquid:depleted_fuel_hecm_245> : stages.progression3,
	<liquid:depleted_fuel_hecm_245_fluoride> : stages.progression3,
	<liquid:depleted_fuel_hecm_245_fluoride_flibe> : stages.progression3,
	<liquid:depleted_fuel_hecm_247> : stages.progression3,
	<liquid:depleted_fuel_hecm_247_fluoride> : stages.progression3,
	<liquid:depleted_fuel_hecm_247_fluoride_flibe> : stages.progression3,
	<liquid:depleted_fuel_hen_236> : stages.progression3,
	<liquid:depleted_fuel_hen_236_fluoride> : stages.progression3,
	<liquid:depleted_fuel_hen_236_fluoride_flibe> : stages.progression3,
	<liquid:depleted_fuel_hep_239> : stages.progression3,
	<liquid:depleted_fuel_hep_239_fluoride> : stages.progression3,
	<liquid:depleted_fuel_hep_239_fluoride_flibe> : stages.progression3,
	<liquid:depleted_fuel_hep_241> : stages.progression3,
	<liquid:depleted_fuel_hep_241_fluoride> : stages.progression3,
	<liquid:depleted_fuel_hep_241_fluoride_flibe> : stages.progression3,
	<liquid:depleted_fuel_heu_233> : stages.progression3,
	<liquid:depleted_fuel_heu_233_fluoride> : stages.progression3,
	<liquid:depleted_fuel_heu_233_fluoride_flibe> : stages.progression3,
	<liquid:depleted_fuel_heu_235> : stages.progression3,
	<liquid:depleted_fuel_heu_235_fluoride> : stages.progression3,
	<liquid:depleted_fuel_heu_235_fluoride_flibe> : stages.progression3,
	<liquid:depleted_fuel_lea_242> : stages.progression3,
	<liquid:depleted_fuel_lea_242_fluoride> : stages.progression3,
	<liquid:depleted_fuel_lea_242_fluoride_flibe> : stages.progression3,
	<liquid:depleted_fuel_leb_248> : stages.progression3,
	<liquid:depleted_fuel_leb_248_fluoride> : stages.progression3,
	<liquid:depleted_fuel_leb_248_fluoride_flibe> : stages.progression3,
	<liquid:depleted_fuel_lecf_249> : stages.progression3,
	<liquid:depleted_fuel_lecf_249_fluoride> : stages.progression3,
	<liquid:depleted_fuel_lecf_249_fluoride_flibe> : stages.progression3,
	<liquid:depleted_fuel_lecf_251> : stages.progression3,
	<liquid:depleted_fuel_lecf_251_fluoride> : stages.progression3,
	<liquid:depleted_fuel_lecf_251_fluoride_flibe> : stages.progression3,
	<liquid:depleted_fuel_lecm_243> : stages.progression3,
	<liquid:depleted_fuel_lecm_243_fluoride> : stages.progression3,
	<liquid:depleted_fuel_lecm_243_fluoride_flibe> : stages.progression3,
	<liquid:depleted_fuel_lecm_245> : stages.progression3,
	<liquid:depleted_fuel_lecm_245_fluoride> : stages.progression3,
	<liquid:depleted_fuel_lecm_245_fluoride_flibe> : stages.progression3,
	<liquid:depleted_fuel_lecm_247> : stages.progression3,
	<liquid:depleted_fuel_lecm_247_fluoride> : stages.progression3,
	<liquid:depleted_fuel_lecm_247_fluoride_flibe> : stages.progression3,
	<liquid:depleted_fuel_len_236> : stages.progression3,
	<liquid:depleted_fuel_len_236_fluoride> : stages.progression3,
	<liquid:depleted_fuel_len_236_fluoride_flibe> : stages.progression3,
	<liquid:depleted_fuel_lep_239> : stages.progression3,
	<liquid:depleted_fuel_lep_239_fluoride> : stages.progression3,
	<liquid:depleted_fuel_lep_239_fluoride_flibe> : stages.progression3,
	<liquid:depleted_fuel_lep_241> : stages.progression3,
	<liquid:depleted_fuel_lep_241_fluoride> : stages.progression3,
	<liquid:depleted_fuel_lep_241_fluoride_flibe> : stages.progression3,
	<liquid:depleted_fuel_leu_233> : stages.progression3,
	<liquid:depleted_fuel_leu_233_fluoride> : stages.progression3,
	<liquid:depleted_fuel_leu_233_fluoride_flibe> : stages.progression3,
	<liquid:depleted_fuel_leu_235> : stages.progression3,
	<liquid:depleted_fuel_leu_235_fluoride> : stages.progression3,
	<liquid:depleted_fuel_leu_235_fluoride_flibe> : stages.progression3,
	<liquid:depleted_fuel_tbu> : stages.progression3,
	<liquid:depleted_fuel_tbu_fluoride> : stages.progression3,
	<liquid:depleted_fuel_tbu_fluoride_flibe> : stages.progression3,
	<liquid:deuterium> : stages.progression2,
	<liquid:diamond> : stages.progression1,
	<liquid:diamond_nak> : stages.progression3,
	<liquid:diamond_nak_hot> : stages.progression3,
	<liquid:diborane> : stages.progression2,
	<liquid:diesel> : stages.progression3,
	<liquid:dirt> : stages.progression1,
	<liquid:draconium> : stages.progression3,
	<liquid:dragonsteel_fire> : stages.progression3,
	<liquid:dragonsteel_ice> : stages.progression3,
	<liquid:electrical_steel> : stages.progression2,
	<liquid:electrum> : stages.progression2,
	<liquid:elemental_water_air> : stages.progression1,
	<liquid:elemental_water_earth> : stages.progression1,
	<liquid:elemental_water_fire> : stages.progression1,
	<liquid:elemental_water_water> : stages.progression1,
	<liquid:elemental_mix> : stages.progression2,
	<liquid:elementium> : stages.Botania3,
	<liquid:emerald> : stages.progression1,
	<liquid:emerald_nak> : stages.progression3,
	<liquid:emerald_nak_hot> : stages.progression3,
	<liquid:end_steel> : stages.progression2,
	<liquid:ender> : stages.progression1,
	<liquid:ender_distillation> : stages.progression2,
	<liquid:ender_nak> : stages.progression3,
	<liquid:ender_nak_hot> : stages.progression3,
	<liquid:enderium> : stages.progression3,
	<liquid:energetic_alloy> : stages.progression2,
	<liquid:energetic_silver> : stages.progression2,
	<liquid:enrichedlava> : stages.progression3,
	<liquid:essence> : stages.progression2,
	<liquid:ethanol> : stages.progression2,
	<liquid:ethene> : stages.progression2,
	<liquid:exhaust_steam> : stages.progression3,
	<liquid:experience> : stages.progression2,
	<liquid:ferroboron> : stages.progression2,
	<liquid:fire_water> : stages.progression2,
	<liquid:flibe> : stages.progression3,
	<liquid:fluorine> : stages.progression2,
	<liquid:fluorite_water> : stages.progression2,
	<liquid:fluoromethane> : stages.progression2,
	<liquid:flux_goo> : stages.progression1,
	<liquid:fuel> : stages.progression3,
	<liquid:fuel_hea_242> : stages.progression3,
	<liquid:fuel_hea_242_fluoride> : stages.progression3,
	<liquid:fuel_hea_242_fluoride_flibe> : stages.progression3,
	<liquid:fuel_heb_248> : stages.progression3,
	<liquid:fuel_heb_248_fluoride> : stages.progression3,
	<liquid:fuel_heb_248_fluoride_flibe> : stages.progression3,
	<liquid:fuel_hecf_249> : stages.progression3,
	<liquid:fuel_hecf_249_fluoride> : stages.progression3,
	<liquid:fuel_hecf_249_fluoride_flibe> : stages.progression3,
	<liquid:fuel_hecf_251> : stages.progression3,
	<liquid:fuel_hecf_251_fluoride> : stages.progression3,
	<liquid:fuel_hecf_251_fluoride_flibe> : stages.progression3,
	<liquid:fuel_hecm_243> : stages.progression3,
	<liquid:fuel_hecm_243_fluoride> : stages.progression3,
	<liquid:fuel_hecm_243_fluoride_flibe> : stages.progression3,
	<liquid:fuel_hecm_245> : stages.progression3,
	<liquid:fuel_hecm_245_fluoride> : stages.progression3,
	<liquid:fuel_hecm_245_fluoride_flibe> : stages.progression3,
	<liquid:fuel_hecm_247> : stages.progression3,
	<liquid:fuel_hecm_247_fluoride> : stages.progression3,
	<liquid:fuel_hecm_247_fluoride_flibe> : stages.progression3,
	<liquid:fuel_hen_236> : stages.progression3,
	<liquid:fuel_hen_236_fluoride> : stages.progression3,
	<liquid:fuel_hen_236_fluoride_flibe> : stages.progression3,
	<liquid:fuel_hep_239> : stages.progression3,
	<liquid:fuel_hep_239_fluoride> : stages.progression3,
	<liquid:fuel_hep_239_fluoride_flibe> : stages.progression3,
	<liquid:fuel_hep_241> : stages.progression3,
	<liquid:fuel_hep_241_fluoride> : stages.progression3,
	<liquid:fuel_hep_241_fluoride_flibe> : stages.progression3,
	<liquid:fuel_heu_233> : stages.progression3,
	<liquid:fuel_heu_233_fluoride> : stages.progression3,
	<liquid:fuel_heu_233_fluoride_flibe> : stages.progression3,
	<liquid:fuel_heu_235> : stages.progression3,
	<liquid:fuel_heu_235_fluoride> : stages.progression3,
	<liquid:fuel_heu_235_fluoride_flibe> : stages.progression3,
	<liquid:fuel_lea_242> : stages.progression3,
	<liquid:fuel_lea_242_fluoride> : stages.progression3,
	<liquid:fuel_lea_242_fluoride_flibe> : stages.progression3,
	<liquid:fuel_leb_248> : stages.progression3,
	<liquid:fuel_leb_248_fluoride> : stages.progression3,
	<liquid:fuel_leb_248_fluoride_flibe> : stages.progression3,
	<liquid:fuel_lecf_249> : stages.progression3,
	<liquid:fuel_lecf_249_fluoride> : stages.progression3,
	<liquid:fuel_lecf_249_fluoride_flibe> : stages.progression3,
	<liquid:fuel_lecf_251> : stages.progression3,
	<liquid:fuel_lecf_251_fluoride> : stages.progression3,
	<liquid:fuel_lecf_251_fluoride_flibe> : stages.progression3,
	<liquid:fuel_lecm_243> : stages.progression3,
	<liquid:fuel_lecm_243_fluoride> : stages.progression3,
	<liquid:fuel_lecm_243_fluoride_flibe> : stages.progression3,
	<liquid:fuel_lecm_245> : stages.progression3,
	<liquid:fuel_lecm_245_fluoride> : stages.progression3,
	<liquid:fuel_lecm_245_fluoride_flibe> : stages.progression3,
	<liquid:fuel_lecm_247> : stages.progression3,
	<liquid:fuel_lecm_247_fluoride> : stages.progression3,
	<liquid:fuel_lecm_247_fluoride_flibe> : stages.progression3,
	<liquid:fuel_len_236> : stages.progression3,
	<liquid:fuel_len_236_fluoride> : stages.progression3,
	<liquid:fuel_len_236_fluoride_flibe> : stages.progression3,
	<liquid:fuel_lep_239> : stages.progression3,
	<liquid:fuel_lep_239_fluoride> : stages.progression3,
	<liquid:fuel_lep_239_fluoride_flibe> : stages.progression3,
	<liquid:fuel_lep_241> : stages.progression3,
	<liquid:fuel_lep_241_fluoride> : stages.progression3,
	<liquid:fuel_lep_241_fluoride_flibe> : stages.progression3,
	<liquid:fuel_leu_233> : stages.progression3,
	<liquid:fuel_leu_233_fluoride> : stages.progression3,
	<liquid:fuel_leu_233_fluoride_flibe> : stages.progression3,
	<liquid:fuel_leu_235> : stages.progression3,
	<liquid:fuel_leu_235_fluoride> : stages.progression3,
	<liquid:fuel_leu_235_fluoride_flibe> : stages.progression3,
	<liquid:fuel_tbu> : stages.progression3,
	<liquid:fuel_tbu_fluoride> : stages.progression3,
	<liquid:fuel_tbu_fluoride_flibe> : stages.progression3,
	<liquid:gas_dwarf> : stages.Embers3,
	<liquid:gasoline> : stages.progression3,
	<liquid:gelatin> : stages.progression1,
	<liquid:glass> : stages.progression1,
	<liquid:glowstone> : stages.progression1,
	<liquid:glowstone_nak> : stages.progression3,
	<liquid:glowstone_nak_hot> : stages.progression3,
	<liquid:gold> : stages.progression1,
	<liquid:gold_nak> : stages.progression3,
	<liquid:gold_nak_hot> : stages.progression3,
	<liquid:hard_carbon> : stages.progression3,
	<liquid:heavy_oil> : stages.progression3,
	<liquid:heavywater> : stages.progression3,
	<liquid:helium> : stages.progression3,
	<liquid:helium3> : stages.progression3,
	<liquid:high_pressure_steam> : stages.progression3,
	<liquid:honey> : stages.progression1,
	<liquid:hootch> : stages.progression2,
	<liquid:hot_crude> : stages.progression3,
	<liquid:hot_spring_water> : stages.progression1,
	<liquid:hydrated_gelatin> : stages.progression1,
	<liquid:hydrofluoric_acid> : stages.progression2,
	<liquid:hydrogen> : stages.progression2,
	<liquid:ice> : stages.progression1,
	<liquid:invar> : stages.progression2,
	<liquid:iridium> : stages.progression3,
	<liquid:iron> : stages.progression1,
	<liquid:iron_nak> : stages.progression3,
	<liquid:iron_nak_hot> : stages.progression3,
	<liquid:juice> : stages.progression2,
	<liquid:kerosene> : stages.progression3,
	<liquid:knightslime> : stages.progression2,
	<liquid:koh> : stages.progression3,
	<liquid:lapis> : stages.progression1,
	<liquid:lapis_nak> : stages.progression3,
	<liquid:lapis_nak_hot> : stages.progression3,
	<liquid:latex> : stages.progression2,
	<liquid:lava> : stages.progression1,
	<liquid:lead> : stages.progression2,
	<liquid:lif> : stages.progression3,
	<liquid:lifeessence> : stages.BloodMagic1,
	<liquid:light_oil> : stages.progression3,
	<liquid:liquid_death> : stages.progression1,
	<liquid:liquid_nightmares> : stages.progression2,
	<liquid:liquid_nitrogen> : stages.progression2,
	<liquid:liquid_sunshine> : stages.progression2,
	<liquid:liquidchlorine> : stages.progression3,
	<liquid:liquiddeuterium> : stages.progression2,
	<liquid:liquidethene> : stages.progression2,
	<liquid:liquidfusionfuel> : stages.progression3,
	<liquid:liquidhelium> : stages.progression3,
	<liquid:liquidhelium_nak> : stages.progression3,
	<liquid:liquidhelium_nak_hot> : stages.progression3,
	<liquid:liquidhydrogen> : stages.progression2,
	<liquid:liquidhydrogenchloride> : stages.progression3,
	<liquid:liquidlithium> : stages.progression3,
	<liquid:liquidoxygen> : stages.progression2,
	<liquid:liquidsodium> : stages.progression3,
	<liquid:liquidsulfurdioxide> : stages.progression2,
	<liquid:liquidsulfurtrioxide> : stages.progression2,
	<liquid:liquidtritium> : stages.progression3,
	<liquid:lithium> : stages.progression3,
	<liquid:lithium6> : stages.progression3,
	<liquid:lithium7> : stages.progression3,
	<liquid:low_pressure_steam> : stages.progression3,
	<liquid:low_quality_steam> : stages.progression3,
	<liquid:lpg> : stages.progression3,
	<liquid:lubricant> : stages.progression2,
	<liquid:lumium> : stages.progression2,
	<liquid:magnesium> : stages.progression3,
	<liquid:magnesium_nak> : stages.progression3,
	<liquid:magnesium_nak_hot> : stages.progression3,
	<liquid:mana> : stages.progression2,
	<liquid:manasteel> : stages.Botania1,
	<liquid:manganese> : stages.progression3,
	<liquid:manganese_dioxide> : stages.progression3,
	<liquid:manyullyn> : stages.progression2,
	<liquid:marshmallow> : stages.progression1,
	<liquid:meat> : stages.progression3,
	<liquid:melodic_alloy> : stages.progression3,
	<liquid:methanol> : stages.progression3,
	<liquid:milk> : stages.progression1,
	<liquid:milk_chocolate> : stages.progression1,
	<liquid:mithril> : stages.progression3,
	<liquid:modularium> : stages.progression3,
	<liquid:molten_reinforced_pink_slime> : stages.progression3,
	<liquid:mushroom_stew> : stages.progression3,
	<liquid:nak> : stages.progression3,
	<liquid:nak_hot> : stages.progression3,
	<liquid:naoh> : stages.progression3,
	<liquid:naphtha> : stages.progression3,
	<liquid:natural_gas> : stages.progression3,
	<liquid:necrodermis> : stages.progression3,
	<liquid:neptunium_236> : stages.progression3,
	<liquid:neptunium_236_fluoride> : stages.progression3,
	<liquid:neptunium_236_fluoride_flibe> : stages.progression3,
	<liquid:neptunium_237> : stages.progression3,
	<liquid:neptunium_237_fluoride> : stages.progression3,
	<liquid:neptunium_237_fluoride_flibe> : stages.progression3,
	<liquid:netherite> : stages.progression1,
	<liquid:neutron> : stages.progression3,
	<liquid:nickel> : stages.progression2,
	<liquid:nitrogen> : stages.progression2,
	<liquid:nutrient_distillation> : stages.progression3,
	<liquid:obsidian> : stages.progression1,
	<liquid:oil> : stages.progression3,
	<liquid:oil_dwarf> : stages.Embers3,
	<liquid:oil_residue> : stages.progression3,
	<liquid:oil_soul> : stages.progression3,
	<liquid:osmium> : stages.progression3,
	<liquid:oxygen> : stages.progression2,
	<liquid:oxygen_difluoride> : stages.progression2,
	<liquid:petrotheum> : stages.progression3,
	<liquid:pewterfluid> : stages.progression3,
	<liquid:pigiron> : stages.progression1,
	<liquid:plasma> : stages.progression3,
	<liquid:plastic> : stages.progression2,
	<liquid:platinum> : stages.progression3,
	<liquid:plutonium> : stages.progression3,
	<liquid:plutonium_238> : stages.progression3,
	<liquid:plutonium_238_fluoride> : stages.progression3,
	<liquid:plutonium_238_fluoride_flibe> : stages.progression3,
	<liquid:plutonium_239> : stages.progression3,
	<liquid:plutonium_239_fluoride> : stages.progression3,
	<liquid:plutonium_239_fluoride_flibe> : stages.progression3,
	<liquid:plutonium_241> : stages.progression3,
	<liquid:plutonium_241_fluoride> : stages.progression3,
	<liquid:plutonium_241_fluoride_flibe> : stages.progression3,
	<liquid:plutonium_242> : stages.progression3,
	<liquid:plutonium_242_fluoride> : stages.progression3,
	<liquid:plutonium_242_fluoride_flibe> : stages.progression3,
	<liquid:plutonium_fluoride> : stages.progression3,
	<liquid:plutonium_fluoride_flibe> : stages.progression3,
	<liquid:poison> : stages.progression1,
	<liquid:potassium> : stages.progression3,
	<liquid:potassium_fluoride_solution> : stages.progression3,
	<liquid:potassium_hydroxide_solution> : stages.progression3,
	<liquid:potato_soup> : stages.progression1,
	<liquid:potion> : stages.progression1,
	<liquid:potion_lingering> : stages.progression1,
	<liquid:potion_splash> : stages.progression1,
	<liquid:preheated_water> : stages.progression3,
	<liquid:pulsating_iron> : stages.progression1,
	<liquid:purifying_fluid> : stages.Thaumcraft3,
	<liquid:purpleslime> : stages.progression2,
	<liquid:pyrotheum> : stages.progression2,
	<liquid:quartz> : stages.progression1,
	<liquid:quartz_nak> : stages.progression3,
	<liquid:quartz_nak_hot> : stages.progression3,
	<liquid:rabbit_stew> : stages.progression1,
	<liquid:radaway> : stages.progression3,
	<liquid:radaway_slow> : stages.progression3,
	<liquid:redstone> : stages.progression1,
	<liquid:redstone_alloy> : stages.progression1,
	<liquid:redstone_nak> : stages.progression3,
	<liquid:redstone_nak_hot> : stages.progression3,
	<liquid:refined_biofuel> : stages.progression2,
	<liquid:refined_fuel> : stages.progression3,
	<liquid:refined_oil> : stages.progression3,
	<liquid:resin> : stages.progression2,
	<liquid:rocket_fuel> : stages.progression3,
	<liquid:rocketfuel> : stages.progression3,
	<liquid:sand> : stages.progression1,
	<liquid:sap> : stages.progression2,
	<liquid:seed_oil> : stages.progression1,
	<liquid:sewage> : stages.progression2,
	<liquid:sic_vapor> : stages.progression3,
	<liquid:signalum> : stages.progression2,
	<liquid:silver> : stages.progression2,
	<liquid:sludge> : stages.progression2,
	<liquid:sodium> : stages.progression3,
	<liquid:sodium_fluoride_solution> : stages.progression3,
	<liquid:sodium_hydroxide_solution> : stages.progression3,
	<liquid:soularium> : stages.progression2,
	<liquid:starmetal> : stages.AstralSorcery2,
	<liquid:steam> : stages.progression1,
	<liquid:steel> : stages.progression2,
	<liquid:stellar_alloy> : stages.progression3,
	<liquid:stone> : stages.progression1,
	<liquid:sugar> : stages.progression1,
	<liquid:sulfur> : stages.progression1,
	<liquid:sulfur_dioxide> : stages.progression2,
	<liquid:sulfur_trioxide> : stages.progression2,
	<liquid:sulfuric_acid> : stages.progression2,
	<liquid:sulfuricacid> : stages.progression2,
	<liquid:syrup> : stages.progression3,
	<liquid:terrasteel> : stages.Botania2,
	<liquid:thaumium> : stages.Thaumcraft1,
	<liquid:thorium> : stages.progression3,
	<liquid:thorium_230> : stages.progression3,
	<liquid:thorium_230_fluoride> : stages.progression3,
	<liquid:thorium_230_fluoride_flibe> : stages.progression3,
	<liquid:thorium_fluoride> : stages.progression3,
	<liquid:thorium_fluoride_flibe> : stages.progression3,
	<liquid:tin> : stages.progression2,
	<liquid:tin_nak> : stages.progression3,
	<liquid:tin_nak_hot> : stages.progression3,
	<liquid:titanium> : stages.progression3,
	<liquid:tough> : stages.progression3,
	<liquid:tree_oil> : stages.progression2,
	<liquid:tritium> : stages.progression3,
	<liquid:tungsten> : stages.progression3,
	<liquid:unsweetened_chocolate> : stages.progression1,
	<liquid:uranium> : stages.progression3,
	<liquid:uranium_233> : stages.progression3,
	<liquid:uranium_233_fluoride> : stages.progression3,
	<liquid:uranium_233_fluoride_flibe> : stages.progression3,
	<liquid:uranium_235> : stages.progression3,
	<liquid:uranium_235_fluoride> : stages.progression3,
	<liquid:uranium_235_fluoride_flibe> : stages.progression3,
	<liquid:uranium_238> : stages.progression3,
	<liquid:uranium_238_fluoride> : stages.progression3,
	<liquid:uranium_238_fluoride_flibe> : stages.progression3,
	<liquid:uranium_fluoride> : stages.progression3,
	<liquid:uranium_fluoride_flibe> : stages.progression3,
	<liquid:vapor_of_levity> : stages.progression2,
	<liquid:vibranium> : stages.progression3,
	<liquid:vibrant_alloy> : stages.progression2,
	<liquid:vivid_alloy> : stages.progression3,
	<liquid:voidmetal> : stages.Thaumcraft3,
	<liquid:water> : stages.progression1,
	<liquid:wood_gas> : stages.progression3,
	<liquid:xpjuice> : stages.progression2,
	<liquid:xu_demonic_metal> : stages.progression1,
	<liquid:xu_enchanted_metal> : stages.progression1,
	<liquid:xu_evil_metal> : stages.progression1,
	<liquid:zinc> : stages.progression2,
};

for liquidObject, zenStageObject in liquidStages
{
	if(zenStageObject.stage != "stage_i")
	{
		//Stage the liquid itself
		mods.ItemStages.stageLiquid(zenStageObject.stage, liquidObject);

		//Stage the Fluid Morb
		StageFlorb(scripts.helpers.getLiquidStringFromObject(liquidObject), zenStageObject);

		//Stage the buckets holding the fluid
		scripts.helpers.setItemAndRecipesStage(scripts.helpers.formatBucket(scripts.helpers.getLiquidStringFromObject(liquidObject)), zenStageObject.stage);

		//Stage ME Fluid Patterns
		StageFluidPattern(scripts.helpers.getLiquidStringFromObject(liquidObject), zenStageObject);

		//Stage Forestry Capsules
		StageForestryCapsule(liquidObject, zenStageObject);
	}
}

print("### Liquid Staging Complete ###");
